import React from 'react'

const Transcript = () => {
    return (
        <div className='transcript h-1/4 space-y-5'>
            <div className='flex-center-between'>
                <h2 className='text-xl lg:text-2xl font-semibold cursor-pointer'>
                    Transcript
                </h2>
                <h2 className='text-md lg:text-lg opacity-50 font-semibold cursor-pointer'>
                    Resources
                </h2>
            </div>
            <div className='pb-5'>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolore, harum commodi assumenda repudiandae aperiam nemo odio porro ipsa nobis esse accusamus quia aliquid quisquam officiis optio rerum fugiat ratione! Nostrum, praesentium magnam. Atque, magnam nobis. Nostrum tempore laudantium, error animi accusantium velit totam aspernatur placeat nemo fugit. Sint perferendis dolores assumenda quas exercitationem expedita. Ipsum, laboriosam. Libero inventore, quas natus suscipit, culpa necessitatibus hic earum voluptas exercitationem voluptate eveniet quisquam doloribus assumenda quo sint! Unde libero fuga id illo ipsum, itaque dolor. Excepturi provident minus voluptatem quo, optio cum ipsam. Expedita natus consequatur id accusamus officiis harum, eligendi modi.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolore, harum commodi assumenda repudiandae aperiam nemo odio porro ipsa nobis esse accusamus quia aliquid quisquam officiis optio rerum fugiat ratione! Nostrum, praesentium magnam. Atque, magnam nobis. Nostrum tempore laudantium, error animi accusantium velit totam aspernatur placeat nemo fugit. Sint perferendis dolores assumenda quas exercitationem expedita. Ipsum, laboriosam. Libero inventore, quas natus suscipit, culpa necessitatibus hic earum voluptas exercitationem voluptate eveniet quisquam doloribus assumenda quo sint! Unde libero fuga id illo ipsum, itaque dolor. Excepturi provident minus voluptatem quo, optio cum ipsam. Expedita natus consequatur id accusamus officiis harum, eligendi modi.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolore, harum commodi assumenda repudiandae aperiam nemo odio porro ipsa nobis esse accusamus quia aliquid quisquam officiis optio rerum fugiat ratione! Nostrum, praesentium magnam. Atque, magnam nobis. Nostrum tempore laudantium, error animi accusantium velit totam aspernatur placeat nemo fugit. Sint perferendis dolores assumenda quas exercitationem expedita. Ipsum, laboriosam. Libero inventore, quas natus suscipit, culpa necessitatibus hic earum voluptas exercitationem voluptate eveniet quisquam doloribus assumenda quo sint! Unde libero fuga id illo ipsum, itaque dolor. Excepturi provident minus voluptatem quo, optio cum ipsam. Expedita natus consequatur id accusamus officiis harum, eligendi modi.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolore, harum commodi assumenda repudiandae aperiam nemo odio porro ipsa nobis esse accusamus quia aliquid quisquam officiis optio rerum fugiat ratione! Nostrum, praesentium magnam. Atque, magnam nobis. Nostrum tempore laudantium, error animi accusantium velit totam aspernatur placeat nemo fugit. Sint perferendis dolores assumenda quas exercitationem expedita. Ipsum, laboriosam. Libero inventore, quas natus suscipit, culpa necessitatibus hic earum voluptas exercitationem voluptate eveniet quisquam doloribus assumenda quo sint! Unde libero fuga id illo ipsum, itaque dolor. Excepturi provident minus voluptatem quo, optio cum ipsam. Expedita natus consequatur id accusamus officiis harum, eligendi modi.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolore, harum commodi assumenda repudiandae aperiam nemo odio porro ipsa nobis esse accusamus quia aliquid quisquam officiis optio rerum fugiat ratione! Nostrum, praesentium magnam. Atque, magnam nobis. Nostrum tempore laudantium, error animi accusantium velit totam aspernatur placeat nemo fugit. Sint perferendis dolores assumenda quas exercitationem expedita. Ipsum, laboriosam. Libero inventore, quas natus suscipit, culpa necessitatibus hic earum voluptas exercitationem voluptate eveniet quisquam doloribus assumenda quo sint! Unde libero fuga id illo ipsum, itaque dolor. Excepturi provident minus voluptatem quo, optio cum ipsam. Expedita natus consequatur id accusamus officiis harum, eligendi modi.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolore, harum commodi assumenda repudiandae aperiam nemo odio porro ipsa nobis esse accusamus quia aliquid quisquam officiis optio rerum fugiat ratione! Nostrum, praesentium magnam. Atque, magnam nobis. Nostrum tempore laudantium, error animi accusantium velit totam aspernatur placeat nemo fugit. Sint perferendis dolores assumenda quas exercitationem expedita. Ipsum, laboriosam. Libero inventore, quas natus suscipit, culpa necessitatibus hic earum voluptas exercitationem voluptate eveniet quisquam doloribus assumenda quo sint! Unde libero fuga id illo ipsum, itaque dolor. Excepturi provident minus voluptatem quo, optio cum ipsam. Expedita natus consequatur id accusamus officiis harum, eligendi modi.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolore, harum commodi assumenda repudiandae aperiam nemo odio porro ipsa nobis esse accusamus quia aliquid quisquam officiis optio rerum fugiat ratione! Nostrum, praesentium magnam. Atque, magnam nobis. Nostrum tempore laudantium, error animi accusantium velit totam aspernatur placeat nemo fugit. Sint perferendis dolores assumenda quas exercitationem expedita. Ipsum, laboriosam. Libero inventore, quas natus suscipit, culpa necessitatibus hic earum voluptas exercitationem voluptate eveniet quisquam doloribus assumenda quo sint! Unde libero fuga id illo ipsum, itaque dolor. Excepturi provident minus voluptatem quo, optio cum ipsam. Expedita natus consequatur id accusamus officiis harum, eligendi modi.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolore, harum commodi assumenda repudiandae aperiam nemo odio porro ipsa nobis esse accusamus quia aliquid quisquam officiis optio rerum fugiat ratione! Nostrum, praesentium magnam. Atque, magnam nobis. Nostrum tempore laudantium, error animi accusantium velit totam aspernatur placeat nemo fugit. Sint perferendis dolores assumenda quas exercitationem expedita. Ipsum, laboriosam. Libero inventore, quas natus suscipit, culpa necessitatibus hic earum voluptas exercitationem voluptate eveniet quisquam doloribus assumenda quo sint! Unde libero fuga id illo ipsum, itaque dolor. Excepturi provident minus voluptatem quo, optio cum ipsam. Expedita natus consequatur id accusamus officiis harum, eligendi modi.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolore, harum commodi assumenda repudiandae aperiam nemo odio porro ipsa nobis esse accusamus quia aliquid quisquam officiis optio rerum fugiat ratione! Nostrum, praesentium magnam. Atque, magnam nobis. Nostrum tempore laudantium, error animi accusantium velit totam aspernatur placeat nemo fugit. Sint perferendis dolores assumenda quas exercitationem expedita. Ipsum, laboriosam. Libero inventore, quas natus suscipit, culpa necessitatibus hic earum voluptas exercitationem voluptate eveniet quisquam doloribus assumenda quo sint! Unde libero fuga id illo ipsum, itaque dolor. Excepturi provident minus voluptatem quo, optio cum ipsam. Expedita natus consequatur id accusamus officiis harum, eligendi modi.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae dolore, harum commodi assumenda repudiandae aperiam nemo odio porro ipsa nobis esse accusamus quia aliquid quisquam officiis optio rerum fugiat ratione! Nostrum, praesentium magnam. Atque, magnam nobis. Nostrum tempore laudantium, error animi accusantium velit totam aspernatur placeat nemo fugit. Sint perferendis dolores assumenda quas exercitationem expedita. Ipsum, laboriosam. Libero inventore, quas natus suscipit, culpa necessitatibus hic earum voluptas exercitationem voluptate eveniet quisquam doloribus assumenda quo sint! Unde libero fuga id illo ipsum, itaque dolor. Excepturi provident minus voluptatem quo, optio cum ipsam. Expedita natus consequatur id accusamus officiis harum, eligendi modi.
            </div>
        </div>
    )
}

export default Transcript
